### PR TITLE
Issue/1091 Fix Simplify give_is_admin_page conditional

### LINKED ISSUE #1091: Simplify give_is_admin_page conditional
## Issue Overview

The `give_is_admin_page` conditional is a giant conditional mess: https://github.com/WordImpress/Give/blob/master/includes/admin/admin-pages.php#L71

It's hard to read and lowers our code quality + scrutinizer score. Let's fix it. 
## Possible Solution

Use `get_current_screen` function and check against a simplified set of conditions.
## Todos
- [ ] Determine whether this function is necessary, it appears only to be in use to conditionally load admin scripts. I only found one other usage within the Recurring add-on. 
- [ ] Figure method to simplify function
- [ ] Develop chosen method
- [ ] Test chosen method

### PR DESCRIPTION
**Pull request by emgk**
## Description

This PR fixes #1091 

## How Has This Been Tested?

- By calling function with params inside `admin_init` hook and compare the result with old function's code.

## Types of changes

 Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/admin/admin-pages.php [hunk 1]
```diff
@@ -111,252 +111,166 @@ function give_add_options_links() {
...
+	$query_args = wp_parse_args( $get_query_args, array_fill_keys( array( 'post_type', 'action', 'taxonomy', 'page', 'view', 'tab' ), false ) );
+
+	// Page expected to pass.
+	$expected_pages = array( 'give_forms', 'categories', 'tags', 'payments', 'reports', 'settings', 'addons', 'donors' );
+
+	// If post type or type is give_forms.
+	if (
+		( 'give_forms' === $typenow || 'give_forms' === $query_args['post_type'] )
+		|| in_array( $passed_page, $expected_pages, true )
+	) {
```
Comment (DevinWalker) [inline includes/admin/admin-pages.php]: Rather than nesting everything in this can you do the opposite condition and pass `$found = false`?
I would prefer less nesting.

Comment (emgk) [reply includes/admin/admin-pages.php]: That will be great, I am working on this. @DevinWalker

Comment (DevinWalker) [reply includes/admin/admin-pages.php]: What's the status on this @emgk ?

**Comment by emgk** [comment]
@DevinWalker Previously the number of lines was **238** after optimizing the code the now number of lines is **95**, lots of nesting conditional has been reduced, also used new function `Give_Admin_Settings::is_setting_page` fn to check setting/reports/addons pages.

**Comment by DevinWalker** [comment]
Thanks @emgk it's looking much better. Can you now finish it up with a solid unit test written for `give_is_admin_page()` that passes both Give and non-Give pages and checks for proper true/false returns?

**Comment by emgk** [comment]
@DevinWalker I am working on PHPUnit testing.

**Comment by emgk** [comment]
@DevinWalker @ravinderk I have added unit test cases for this.  https://github.com/WordImpress/Give/pull/2639/commits/360614fb0754d186fac56ec60f3ee4b6836a207e

**Comment by DevinWalker** [comment]
Good job on this one @emgk 👍
