### PR TITLE
Issues/576

### LINKED ISSUE #576: Fill form fields with previously entered validated values on give_send_back_to_checkout()
When a guest user fills out the payment form and the transaction fails with a soft error (e.g. country validation, card is declined, bad cvc, etc.), it redirects them back to the form and shows the transaction error notice. However, because the user is a guest and has not logged in or created an account, they have to fill out the entire form all over again for a second attempt.

I suggest sending validated values back to the form and have the form template functions use the $_REQUEST field values if they exist.

```
give_send_back_to_checkout( '?' . http_build_query( $validated_form_values ) );
```

### PR DESCRIPTION
**Pull request by ravinderk**
This pr will fix #576 

## Description
This pr adds feature to auto auto fill previously added form field values by donor (guest/logged in), if donor redirect to donation form due to some error .
Form sections which will auto populate:
- [x] Select Payment Method
- [x] Personal Info
- [ ] Credit Card Info
- [x] Billing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: includes/forms/template.php [hunk 1]
```diff
@@ -848,86 +862,104 @@ function give_default_cc_address_fields( $form_id ) {
 			<label for="card_address" class="give-label">
 				<?php esc_html_e( 'Address 1', 'give' ); ?>
 				<?php
-				if ( give_field_is_required( 'card_address', $form_id ) ) { ?>
+				if ( give_field_is_required( 'card_address', $form_id ) ) : ?>
```
Comment (DevinWalker) [inline includes/forms/template.php]: Can we stick with using brackets? It improves the Scrutinizer score and I'd like to stick with them throughout the project.

File: includes/forms/template.php [hunk 2]
```diff
@@ -668,9 +675,14 @@ function give_user_info_fields( $form_id ) {
 				<span class="give-tooltip give-icon give-icon-question" data-tooltip="<?php esc_attr_e( 'We will send the donation receipt to this address.', 'give' ); ?>"></span>
 			</label>
 
-			<input class="give-input required" type="email" name="give_email" placeholder="<?php esc_attr_e( 'Email Address', 'give' ); ?>" id="give-email" value="<?php echo is_user_logged_in() ? $user_data->user_email : ''; ?>"<?php if ( give_field_is_required( 'give_email', $form_id ) ) {
-				echo ' required ';
-			} ?>/>
+			<input
```
Comment (DevinWalker) [inline includes/forms/template.php]: Spacing for clarity?

File: includes/forms/functions.php [hunk 3]
```diff
@@ -876,4 +876,72 @@ function give_show_login_register_option( $form_id ) {
...
+			// City.
+			'card_city'      => ( ! empty( $donor_address['city'] ) ? $donor_address['city'] : '' ),
+
+			// Zipcode
+			'card_zip'       => ( ! empty( $donor_address['zip'] ) ? $donor_address['zip'] : '' )
+		);
+	endif;
+
+	// Bailout: Auto fill form field values only form form which donor is donating.
+	if(
```
Comment (DevinWalker) [inline includes/forms/functions.php]: I see this conditional hasn't changed much besides moving down. Is the issue we discussed last night resolved?

File: includes/forms/template.php (hunk 2 above)
Comment (ravinderk) [inline includes/forms/template.php]: Yes

File: includes/forms/functions.php (hunk 3 above)
Comment (ravinderk) [inline includes/forms/functions.php]: Yes that issue has been resolved. I return $logged_in_donor_info instead or empty array which contain logged in donor info otherwise empty.

**Comment by DevinWalker** [comment]
If you're logged in, the donation form properly uses your name + email. However, if you're logged in and choose another name + email and there's a validation error the form will revert to your logged in profiles info rather than the one you just entered:

xhbej4uhgq

**Comment by DevinWalker** [comment]
Working great now, thanks!
