### PR TITLE
Fix: #1278

### LINKED ISSUE #1278: Sometimes expiration field in form stops auto formatting date
## Issue Overview
I am also getting same behavior in `master` branch.

cb4ic3tuij

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will resolve #1278 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: assets/js/frontend/give-checkout-global.js [hunk 1]
```diff
@@ -66,30 +66,29 @@ jQuery(function ($) {
...
-			var card_cvc    = $(this).find('.card-cvc');
-			var card_expiry = $(this).find('.card-expiry');
+		$give_form.each(function (index, form) {
+			form            = $(form);
+			var card_number = form.find('.card-number'),
+				card_cvc    = form.find('.card-cvc'),
+				card_expiry = form.find('.card-expiry');
 
 			//Only validate if there is a card field
-			if (card_number.length === 0) {
```
Comment (ravinderk) [inline assets/js/frontend/give-checkout-global.js]: @DevinWalker main problem was with this condition. so if we have multiple forms on the same page and first donation form does not have any cc fields then instead of skipping the current form and process others, it was exiting the loop, so no formatting event fire for other forms.

Comment (DevinWalker) [inline assets/js/frontend/give-checkout-global.js]: Gotcha! Good catch.
