### PR TITLE
Issues 2280

### LINKED ISSUE #2280: Unable to change donation level within donation details edit screen
## Issue Overview
When I attempt to change the donation level using the dropdown I am unable to do so:

## Expected Behavior
The level should change the amount accordingly and it should also work with Fee Recovery by adjusting the amount plus the fees:

## Current Behavior
Only manually changing the amount works. The dropdown is useless.

## Steps to Reproduce (for bugs)
1. Give + Fee Recovery
2. View a donation on multi-level form
3. Attempt to change the level and save

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
This PR will resolve  #2280 

## How Has This Been Tested?
See the Video to know how this is being tested
Video: http://youtu.be/e3J-Bc2iHq0?hd=1

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@ravinderk 

Need to discuss this PR with you

File: assets/js/admin/admin-scripts.js [hunk 1]
```diff
@@ -2234,7 +2234,7 @@ var give_setting_edit = false;
 
 			// Back out.
 			if (give_unformat_currency('0', false) === give_unformat_currency($(this).val(), false)) {
-				$(this).val('');
+				$(this).val('0');
```
Comment (ravinderk) [inline assets/js/admin/admin-scripts.js]: @DevinWalker we will set zero instead of an empty string if admin will leave amount/money field empty.
