### PR TITLE
Email access improvements

### LINKED ISSUE #2304: Problem with email access due to complication with #1790
@Benunc commented on [Tue Nov 07 2017](https://github.com/WordImpress/Give-Recurring-Donations/issues/418)

## Issue Overview

Currently if email access is enabled, donors cannot access their donation history as expected.

## Expected Behavior
The Give_subscriptions shortcode should work correctly.

## Current Behavior
screen shot 2017-11-07 at 11 32 47 am

## Possible Solution
Review complication with #1790 causing email access to not work as expected. 

## Steps to Reproduce (for bugs)

**Original steps from @Benunc**
1. On Give 1.8.16 and Recurring 1.4 branch (pre-release)
2. Create some subscriptions, as well as a page with the [give_subscriptions] shortcode.
3. Ensure that email access is enabled.
4. In an incognito browser, navigate to the page with the above shortcode on it
5. Attempt to enter a valid email that has made a recurring donation on the site.

**I was able to reproduce with the donation history page, and other locations the email access is in use. Essentially, email access is not working now.**

You will get the above error 

> Error: It looks like that email address provided and access token of the link does not match.

## Related issues
https://github.com/WordImpress/Give/issues/1790

### PR DESCRIPTION
**Pull request by DevinWalker**
## Description
I've addressed issues we've reviewed in https://github.com/WordImpress/Give/issues/2304 and improved the workflow.

1. Reworked requesting history access
2. reCaptcha works as expected
3. Moved functionality to new function 
4. Verified throttle works
5. Settings ironed out

Fixes #2304 #2474 

## Types of changes
- UX improvement
- Code improvement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by mehul0810** [comment]
@DevinWalker Receipt Access area when session is expired is broken. 

## Steps to Reproduce
1. Perform a Donation
2. Check Donation Receipt Email.
3. Copy `View it in browser` link
4. Open in incognito mode
5. Try accessing the donation receipt after entering email.

gif

File: includes/ajax-functions.php [hunk 1]
```diff
@@ -561,8 +561,8 @@ function give_confirm_email_for_donation_access() {
 		$return['status']  = 'error';
 		$return['message'] = Give()->notices->print_frontend_notice(
 			sprintf(
-				__( 'Please refresh the page in %s minutes before requesting a new donation history access link.', 'give' ),
-				$value
+				__( 'Too many access email requests detected. Please wait %s before requesting a new donation history access link.', 'give' ),
+				sprintf( _n( '%s minute', '%s minutes', Give()->email_access->verify_throttle / 60, 'give' ), Give()->email_access->verify_throttle / 60 )
```
Comment (ravinderk) [inline includes/ajax-functions.php]: @DevinWalker Can we use `$value` instead of recalculating `Give()->email_access->verify_throttle / 60`

Comment (DevinWalker) [reply includes/ajax-functions.php]: Done
