### PR TITLE
Issues/2461

### LINKED ISSUE #2461: Donation total not respect to the number of decimal
## Issue Overview

- Donation total does not respect to the number of decimal while switching on donation amount value.
- Same with Custom amount
- Issue exist on latest Give 1.8.17

nimbus-record-video-2017-12-06-11-07-12

## Expected Behavior

- The number of decimal should remain same when switching to the donation amount or gateway.

## Current Behavior

- Currently, It does not remain same and change from  $10.00 to $10 while switching to the amount.
- Also with the Custom amount, it does not work.

## Steps to Reproduce (for bugs)

1. Create a donation form with Multi-level donation with various amount
2. Switching among the amount 
3. As you can see that decimal value does not remain same when switching

## Todos
- [ ] Tests

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://givewp.dev
Site URL: http://givewp.dev
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewp.dev
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 1.8.17
Upgraded From: 1.8.17
Test Mode: Enabled
Currency Code: INR
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givewp.dev/donation-confirmation/
Failure Page: http://givewp.dev/donation-failed/
Donation History Page: http://givewp.dev/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###


### Other Active Plugins ###


### Inactive Plugins ###

Give - Currency Switcher: by WordImpress – 1.0.0
Give - Fee Recovery: by WordImpress – 1.3.2
Give - Form Field Manager: by WordImpress – 1.2.3
Give - Gift Aid: by WordImpress – 1.0.0
Give - PDF Receipts: by WordImpress – 2.1
Give - Recurring Donations: by WordImpress – 1.4
Give - Setting API Fields Example: by WordImpress – 1.0
Give - Stripe Gateway: by WordImpress – 1.5
Give - Tributes: by WordImpress – 1.2

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will resolve #2461 

## How Has This Been Tested?

Since this issue was with `INR` currency formatting then I tested it with that currency only.

## Screenshots (jpeg or gifs if applicable):
alpk8mtdx8

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: assets/js/frontend/give-donations.js [hunk 1]
```diff
@@ -98,6 +98,8 @@ Give = {
 					} else if (( args.precision + 1 ) > decimal_amount.length) {
 						decimal_amount = ( decimal_amount + '000000000' ).substr(0, args.precision + 1);
 					}
+				}else {
```
Comment (jaydeeprami) [inline assets/js/frontend/give-donations.js]: @ravinderk, Need to correct formatting here.

Comment (ravinderk) [reply assets/js/frontend/give-donations.js]: @jaydeeprami Fixed

Comment (jaydeeprami) [reply assets/js/frontend/give-donations.js]: Thanks @ravinderk
