### PR TITLE
Issues 2235

### LINKED ISSUE #2235: Recalculate Income Amount and Donation Counts for All Forms tool is not working as intended
## Issue Overview
Recalculate Income Amount and Donation Counts for All Forms tool is not working as intended but recalculating income amount and donation for a form is working as intended.

My local setup is the one where all the donations are done in test mode. So I made a clone of my local setup ( I use Local by Flywheel ). In the cloned setup I deleted all the test donor and test payments using the "Delete test donors and payments " data tool and after that I used "Recalculate Income Amount and Donation Counts for All Forms" tool.
This deleted all the donations ( except the abandoned ones) and all the donation amount from donors but not the donors itself. This did not clear the total income and donation numbers in all forms. I tried "Recalculate Income Amount and Donation Counts for All Forms" tool couple of times to confirm. Then when I tried "Recalculate Income Amount and Donation for a form" it worked for that form as intended.

I will be adding all the related screenshots from my original local setup and cloned setup for better understanding.

## Expected Behavior
Recalculate Income Amount and Donation Counts for All Forms tool should work as intended.

## Current Behavior
Recalculate Income Amount and Donation Counts for All Forms tool is not working as intended and does not update the donations total income and total donations.

## Steps to Reproduce (for bugs)
Go Donations >> Tools >> Data >> Delete Test Donors and Payments then try "Recalculate Income Amount and Donation Counts for All Forms" and check Donations, donors and All forms.

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/1905

## Related HelpScout ticket
https://secure.helpscout.net/conversation/454805474/11170/?folderId=1457790

## System Info
WordPress - 4.8.2
Give - 1.8.15
Give - Authorize.net Gateway – 1.2.3
Give - Braintree Gateway – 1.1.1 
Give - Form Field Manager  – 1.2.3
Give - PayPal Pro Gateway – 1.1.4
Give - Recurring Donations – 1.3.1
Give - Stripe Gateway – 1.5
Give - Tributes  – 1.2
Email Cop: by Ashfame – 0.1.1

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
This PR will resolve  #2235 #2299 

## How Has This Been Tested?
Manually Tested

ScreenShort:
Image of issues: #2299 
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk 

Kindly please review the PR and merge

**Comment by ravinderk** [comment]
@raftaar1191 After successfully complete process JS only set both fields but not unset value of the second field. To run the process again I have chosen same form option again.

e20oxcb9np

**Comment by raftaar1191** [comment]
@ravinderk 

Nice Catch. I don't know how did I miss that. Working on this right now

**Comment by raftaar1191** [comment]
@ravinderk 

Fixed 
main

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk 

Please review and merge this PR

File: includes/admin/tools/views/html-admin-page-data.php [hunk 1]
```diff
@@ -56,7 +56,8 @@
 						$args = array(
 							'name'   => 'form_id',
 							'number' => - 1,
-							'chosen' => true,
+							'chosen' => false,
```
Comment (DevinWalker) [inline includes/admin/tools/views/html-admin-page-data.php]: @raftaar1191 why are you disabling `chosen`?

Comment (raftaar1191) [reply includes/admin/tools/views/html-admin-page-data.php]: Because after the ajax complete we need to reset the `Form` to it's default value and chosen was creating some issues. So I thought to remove it 

Without chosen parameter:
image

With Chosen parameter:
image

@DevinWalker Have a look at the images I don't think it making a much more diff. If you want I can again add that

Comment (DevinWalker) [reply includes/admin/tools/views/html-admin-page-data.php]: @raftaar1191 I'd rather keep it since if you have a lot of forms it's helpful. As well, it should use AJAX to lookup forms not present in the dropdown options. There's a param for that.

The first option should actually say 

> Select Form

Not plural "forms" since you can only select one.

Comment (raftaar1191) [reply includes/admin/tools/views/html-admin-page-data.php]: Okay @DevinWalker adding that

Oop I did not see that `Select Forms` chaining that

Comment (raftaar1191) [reply includes/admin/tools/views/html-admin-page-data.php]: @DevinWalker Code Updated

Screensort :
image

File: includes/admin/tools/views/html-admin-page-data.php [hunk 2]
```diff
@@ -54,9 +54,11 @@
 					<span class="tools-form-dropdown tools-form-dropdown-recount-form" style="display: none">
 						<?php
 						$args = array(
+							'class'   => 'tools-form-dropdown-recount-form-select',
 							'name'   => 'form_id',
 							'number' => - 1,
 							'chosen' => true,
+							'placeholder' => 'Select Form',
```
Comment (ravinderk) [inline includes/admin/tools/views/html-admin-page-data.php]: @raftaar1191 Why we have text without  i18n fn?

Comment (raftaar1191) [reply includes/admin/tools/views/html-admin-page-data.php]: Fixing that

File: assets/js/admin/admin-scripts.js [hunk 3]
```diff
@@ -974,8 +978,12 @@ var give_setting_edit = false;
 						});
 						self.process_step(parseInt(response.step), data, self);
 					}
-					// Reset the form for preventing multiple ajax request.
-					$('#give-tools-recount-form')[0].reset();
+
+					if ( true === reset_form ) {
```
Comment (ravinderk) [inline assets/js/admin/admin-scripts.js]: @DevinWalker `Give_Reports` and `Give_Exports` share same `form` tag and `process_step` fn, so to reset form @raftaar1191 edit `process_step` which is running for both. It will not create any issue but it is better to refactor code that allows us to maintain both.  I can see we are using process step many places in admin backend it will be a good idea if we will create a global function within `Give` object as we are doing in the frontend. We can do that after `2.0`.

@DevinWalker Let me know what do you think
