### PR TITLE
Fix plural and singular context of import completions message #2767

### LINKED ISSUE #2767: Correct message after successfully importing donations
## Issue Overview
If the file to be imported has 1 record and is successfully imported or failed, the message shows:
`Import complete! 1 donations processed` 

## Expected Behavior
For 1 record, the message should say "donation" instead of "donations" for both success and failure message.

## Current Behavior
For success/failure of 1 record import, the message is given in a plural context instead of singular

## Steps to Reproduce (for bugs)
1. **Tools > Import**
2. Import a CSV with 1 record

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to fix #2767 

## How Has This Been Tested?
Manually test by import the CSV and check the message

## Screenshots (jpeg or gifs if applicable):
image

image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/admin/tools/import/class-give-import-donations.php [hunk 1]
```diff
@@ -253,12 +253,12 @@ public function import_success() {
 						<?php
 						if ( $success ) {
 							echo sprintf(
```
Comment (Sidsector9) [inline includes/admin/tools/import/class-give-import-donations.php]: Use `printf()` instead of `echo sprintf()`

File: includes/admin/tools/import/class-give-import-donations.php [hunk 2]
```diff
@@ -253,12 +253,12 @@ public function import_success() {
...
-								__( 'Import complete! %s donations processed', 'give' ),
+								_n( 'Import complete! %s donation processed', 'Import complete! %s donations processed', $total, 'give' ),
 								"<strong>{$total}</strong>"
 							);
 						} else {
 							echo sprintf(
```
Comment (Sidsector9) [inline includes/admin/tools/import/class-give-import-donations.php]: Same here @raftaar1191

File: includes/admin/tools/import/class-give-import-donations.php (hunk 1 above)
Comment (raftaar1191) [reply includes/admin/tools/import/class-give-import-donations.php]: Got it @Sidsector9 fixing that

File: includes/admin/tools/import/class-give-import-donations.php (hunk 2 above)
Comment (raftaar1191) [reply includes/admin/tools/import/class-give-import-donations.php]: Got it @Sidsector9 fixing that

**Comment by raftaar1191** [comment]
@Sidsector9 it being fixed can you please review it

**Comment by Sidsector9** [comment]
@raftaar1191 @ravinderk Looks cool :+1:
