### PR TITLE
Issues/2305

### LINKED ISSUE #2305: Issue with new getPriceID when levels share the same price
## Issue Overview
Sometimes a donation form may have several levels with the same price. For instance, with recurring you could have several "Admin Choice" options:

Having a form like this creates unclickable levels on the frontend.

## Expected Behavior
Clicking through the levels always works as expected.

## Current Behavior
Only the first amount within that due to `getPriceID` logic within `give-donations.js`:

## Steps to Reproduce (for bugs)
1. Create a donation form as pictured above
2. View the form on the frontend
3. Attempt clicking through the various levels

## Related Issues and/or PRs
https://github.com/WordImpress/Give/pull/2255

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will fix #2305 #2292 .

615joexk0n

@DevinWalker you can see in above gif that if I will select `$5` amount other then the first amount and then after clicking on amount field will reset it to first `$5`. This can cause choosing wrong donation level means the donor can change mind., so I improved algorithm which will choose recent price id of the same amount chosen by a donor.

kpdm3geajw

## How Has This Been Tested?

Manually testing form with multiple levels of same amount.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: assets/js/frontend/give-donations.js [hunk 1]
```diff
@@ -13,6 +13,25 @@ var give_scripts, give_global_vars;
 var Give = 'undefined' !== typeof Give ? Give : {};
 
 Give = {
+	init: function () {
+		var subHelperObjs = ['form'],
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker i added logic to main `init` function to initialise sub objects `init` function (if any). Also added two event. 

Please check event naming because we will following if you agree. Chosen is following same naming pattern.

File: assets/js/frontend/give-donations.js [hunk 2]
```diff
@@ -162,14 +181,76 @@ Give = {
...
+		/**
+		 * set cache
+		 *
+		 * @since 1.8.17
+		 *
+		 * @param {string} key
+		 * @param {string} value
+		 * @param {object} $form
+		 */
+		setCache: function (key, value, $form) {
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker I added caching api.

File: assets/js/frontend/give-donations.js [hunk 3]
```diff
@@ -162,14 +181,76 @@ Give = {
...
+			return cache;
+		},
+
+		/**
+		 * Initialize cache.
+		 *
+		 * @since 1.8.17
+		 * @private
+		 */
+		__initialize_cache: function () {
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker this class will initialise empty cache for each donation form on current page

File: assets/js/frontend/give-donations.js [hunk 4]
```diff
@@ -162,14 +181,76 @@ Give = {
...
 	}
-};
+	,
+
+	/**
+	 * This object key will be use to cache predicted data or donor activity.
+	 *
+	 * @since 1.8.17
+	 */
+	cache: {}
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker This object key will contain all cache

File: assets/js/frontend/give-donations.js [hunk 5]
```diff
@@ -248,6 +327,10 @@ Give.form = {
 					}
 					break;
 
+				case 'form-id':
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker Added new get info data

File: assets/js/frontend/give-donations.js [hunk 6]
```diff
@@ -992,6 +1089,20 @@ jQuery(function ($) {
 		$('a.give_terms_links', $fieldset_wrapper).toggle();
 		return false;
 	});
+
+	/**
+	 * Prevent level jump which happen due to same id.
+	 * @see https://github.com/WordImpress/Give/issues/2292
+	 */
+	$('label[for^="give-radio-level"]').on('click', function (e) {
```
Comment (ravinderk) [inline assets/js/frontend/give-donations.js]: @DevinWalker this is quick fix for  https://github.com/WordImpress/Give/issues/2292. I think we need a logic to generate unique for donation form and also update logic (javascript mainly) which depends upon form or it's element ids.

Let me know what do you think.

**Comment by ravinderk** [comment]
@DevinWalker I created a video of testing https://youtu.be/0pwy47MXA5Y

File: assets/js/frontend/give-donations.js (hunk 6 above)
Comment (DevinWalker) [reply assets/js/frontend/give-donations.js]: @ravinderk I agree. Each form embedded on a page should have a _unique_ ID. That means even if you're embedding the _same_ form on a page the twice that the two forms will still have _unique_ IDs. We're running into issues where people embedded the same for on a page which means duplicate IDs are in use within HTML (breaks semantic markup and validation) and also causes some complications with jumping between the forms for certain form elements.
