### PR TITLE
Issue/2562

### LINKED ISSUE #2562: Donations get processed with Empty First Name
## Issue Overview
I've noticed an issue that empty first name processes the donation when whitespaces are added as First Name which is not good.

**Check Video for more details:** https://drive.google.com/open?id=1voEFLZh3JHE7w4c2qmR7Q3ueWJrsUoyt
 
## Expected Behavior
Donations should not get processed with empty required fields.

## Current Behavior
First Name with whitespaces processes the donation.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.local
Site URL: http://give20.local
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instruction✔New Donor Register✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.local/donation-confirmation/
Failure Page: http://give20.local/donation-failed/
Donation History Page: http://give20.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.3.5
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

### PR DESCRIPTION
**Pull request by mehul0810**
## Description
This PR resolves #2562 

## How Has This Been Tested?
I've tested this with Client Side Validation as well as Server Side Validation to make sure the donation form doesn't bypass the required fields and process the donation.

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@mehul0810 what is my name has a space in it like "Mc Cringleberry"?

**Comment by mehul0810** [comment]
@DevinWalker Currently, I've implemented it considering that if user enters `First Name` and `Last Name` into First Name column that can create unexpected issue. So, if user enters `Mc Cringleberry` in Firstname then it won't accept. But, if it is entered without space then Firstname will accept it. Let me know if you like to allow whitespace in First Name Form Field. I'll make those changes.

**Comment by kevinwhoffman** [comment]
It is pretty common in the US for first names to include white space. `Mary Jo`, `John Paul`, `Anna Marie`, etc. I think we need to allow it.

File: includes/forms/template.php [hunk 1]
```diff
@@ -648,6 +650,8 @@ class="give-input required"
 					name="give_first"
 					placeholder="<?php _e( 'First Name', 'give' ); ?>"
 					id="give-first"
+					pattern="[A-Za-z]+"
```
Comment (DevinWalker) [inline includes/forms/template.php]: Ditch this because we're likely moving away from HTML5 validation in the future.

File: includes/process-donation.php [hunk 2]
```diff
@@ -1233,3 +1221,25 @@ function give_validate_donation_amount( $valid_data, $data ) {
...
 add_action( 'give_checkout_error_checks', 'give_validate_donation_amount', 10, 2 );
+
+/**
+ * Validate Required Form Fields.
+ *
+ * @param int $form_id Form ID.
+ *
+ * @since 2.0
+ */
+function give_validate_required_form_fields( $form_id ) {
```
Comment (DevinWalker) [inline includes/process-donation.php]: Nice clean up here.

File: includes/process-donation.php [hunk 3]
```diff
@@ -1233,3 +1221,25 @@ function give_validate_donation_amount( $valid_data, $data ) {
...
+
+	// Loop through required fields and show error messages.
+	foreach ( give_get_required_fields( $form_id ) as $field_name => $value ) {
+
+		// Clean Up Data of the input fields.
+		$field_value = give_clean( $_POST[ $field_name ] );
```
Comment (DevinWalker) [inline includes/process-donation.php]: 👍

**Comment by mehul0810** [comment]
@DevinWalker I've removed the `pattern` attribute. Also, First Name field will not validate if only whitespaces entered. However, it will validate with server side validation. Let me know your thoughts.

**Comment by DevinWalker** [comment]
Serverside is fine @mehul0810
