### PR TITLE
fix(compat): resolve caching conflict with W3TC

### LINKED ISSUE #2832: fix(compat): create a test environment for Microsoft server-related issues
## Issue Overview
Increasingly in support, we get tickets with Microsoft servers, where issues are difficult to replicate in a Linux/Docker local environment. 

This issue has two goals: 
1. Establish a set of best practices for the support team and Dev team to work together to resolve windows server issues.
2. Establish a shared environment or set of environments where Windows server setups can be replicated.

## Expected Behavior
If a customer submits a ticket with Microsoft IIS 7.5 and PHP 5.4 we need a way to replicate that server environment in the same way I can replicate LAMP environments. 

## Current Behavior
I was able to spin up one Microsoft Azure site, but it's (a) running IIS 10 and I don't see a way to switch that and (b) possibly costing me money to run. (I had to submit a card number to get signed up)

To exacerbate the need, I currently have one ticket where PDF receipts is not working at all on the customer's site and another with an Ajax error that I can't replicate elsewhere

## Related
- https://secure.helpscout.net/conversation/590682811/19296?folderId=848135
- https://secure.helpscout.net/conversation/524868261/14400/?folderId=672199

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will close #2832.

## How Has This Been Tested?

Manually by performing donation.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/class-give-cache.php [hunk 1]
```diff
@@ -79,6 +79,77 @@ public function setup() {
...
+		}
+
+		$config   = w3_instance( 'W3_Config' );
+		$enabled  = $config->get_integer( 'dbcache.enabled' );
+		$settings = array_map( 'trim', $config->get_array( 'dbcache.reject.sql' ) );
+
+		if ( $enabled && ! in_array( 'give', $settings, true ) ) {
+			?>
+			<div class="error">
+				<p><?php echo wp_kses_post( sprintf( __( 'In order for <strong>database caching</strong> to work with Give you must add %1$s to the "Ignored Query Strings" option in <a href="%2$s">W3 Total Cache settings</a>.', 'woocommerce' ), '<code>give</code>', esc_url( admin_url( 'admin.php?page=w3tc_dbcache' ) ) ) ); ?></p>
```
Comment (DevinWalker) [inline includes/class-give-cache.php]: Incorrect textdomain. I can update this.
