### PR TITLE
Issues/2241

### LINKED ISSUE #2241: Add-on activation banners aren't displaying anymore
## Issue Overview
When I activate an add-on on a fresh install it isn't appearing:

## Expected Behavior
Activation banners display

## Current Behavior
They are not displaying

## Steps to Reproduce (for bugs)

1. Fresh WP
2. Install Give
3. Install Add-on
4. Activate Add-on

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will fix #2241 

## How Has This Been Tested?

1. Activating addons
2. Changing WordPress locale

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/class-notices.php [hunk 1]
```diff
@@ -121,6 +121,16 @@ public function register_notice( $notice_args ) {
...
+				 * Add custom notice html
+				 * Note: This param has more priority then description, so if you have  both param then this one will be use
+				 *       for generating notice html. Most of feature of notice attach to core generated html, so if you set
+				 *       custom html then please add required classes and data attribute which help to apply feature on notice.
+				 *
+				 * @since 1.8.16
+				 */
+				'description_html'      => '',
+
+				/*
```
Comment (ravinderk) [inline includes/class-notices.php]: @DevinWalker check this new feature for html
