### PR TITLE
Issues/850

### LINKED ISSUE #1175: Clean up Donor search results URLs
## Issue Overview

When searching for Donors, the search results URLs contain `_wpnonce` and `_wp_http_referer` query args. These args should be removed prior to redirection.
### Example URL for Search Results from Donor Reports Tab

`http://give.dev/wp-admin/edit.php?_wpnonce=577d19d542&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_type%3Dgive_forms%26page%3Dgive-reports%26tab%3Ddonors&s=test&paged=1&post_type=give_forms&page=give-reports&tab=donors`
## Expected Behavior

The search results URL should not contain `_wpnonce` and `_wp_http_referer` query args.
## Current Behavior

`_wpnonce` and `_wp_http_referer` query args are present in search results URLs. The `_wp_http_referer` query arg compounds in length with each successive search.
## Possible Solution

I looked into how WP core handles nonce fields during a search query, and I found that those arguments are removed in `edit.php` prior to redirecting to search results. Here are the relevant lines: https://github.com/WordPress/WordPress/blob/master/wp-admin/edit.php#L175-L178

I tried placing that same code at the top of `reports.php`:

```
if ( ! empty($_REQUEST['_wp_http_referer']) ) {
     wp_redirect( remove_query_arg( array('_wp_http_referer', '_wpnonce'), wp_unslash($_SERVER['REQUEST_URI']) ) );
     exit;
}
```

However, that code results in `Fatal error: Uncaught Error: Call to undefined function wp_redirect()`.

We should determine if the nonce field is even serving a purpose here, or alternatively find a way to remove the query args from the URL.
## Steps to Reproduce (for bugs)
1. Visit Reports > Donors tab in Give `1.8.0`.
2. Submit a search query in the top-right corner.
3. Note the query `_wpnonce` and `_wp_http_referer` query args in the URL.
4. Submit another search query an notice the `_wp_http_referer` compounds in length.
## Todos
- [ ] Determine if the nonce field serves a purpose in this context. @DevinWalker

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This pr will fix #1175 and #850.

## Screenshots (jpeg or gifs if applicable):
hvpthhpgt8

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ravinderk** [comment]
@DevinWalker Do you want to show notices for all bulk actions?
screen shot 2016-11-24 at 9 32 33 pm

**Comment by DevinWalker** [comment]
@ravinderk no just for delete for now.

File: includes/scripts.php [hunk 1]
```diff
@@ -310,6 +310,11 @@ function give_load_admin_scripts( $hook ) {
 		'confirm_before_remove_row_text' => __( 'Do you want to delete this level?', 'give' ),
 		'matched_success_failure_page'   => __( 'You cannot set the success and failed pages to the same page', 'give' ),
 		'dismiss_notice_text'            => __( 'Dismiss this notice.', 'give' ),
+		'bulk_action' => array(
+			'zero_payment_selected' => __( 'Please choose some payments to delete', 'give' ),
```
Comment (DevinWalker) [inline includes/scripts.php]: Please change text to "You must choose at least one or more payments to delete."

File: includes/scripts.php [hunk 2]
```diff
@@ -310,6 +310,11 @@ function give_load_admin_scripts( $hook ) {
...
+			'delete_payment'        => __( 'Do you want permanently delete only one transaction?', 'give' ),
```
Comment (DevinWalker) [inline includes/scripts.php]: Please change the text to "Are you sure you want to permanently delete this donation?"

File: includes/scripts.php [hunk 3]
```diff
@@ -310,6 +310,11 @@ function give_load_admin_scripts( $hook ) {
...
+			'delete_payments'       => __( 'Do you want permanently delete {payment_count} number of transactions?', 'give' ),
```
Comment (DevinWalker) [inline includes/scripts.php]: Please change text to "Are you sure you want to permanently delete the selected {payment_count} donations?"

File: includes/admin/class-admin-notices.php [hunk 4]
```diff
@@ -209,6 +218,36 @@ function dismiss_notices() {
...
+
+
+	/**
+	 * Add payment bulk notice.
+	 *
+	 * @since 1.8
+	 *
+	 * @return array
+	 */
+	function add_payment_bulk_action_notice() {
```
Comment (DevinWalker) [inline includes/admin/class-admin-notices.php]: Nice! 👍

**Comment by ravinderk** [comment]
@DevinWalker PR updated.

**Comment by ravinderk** [comment]
@DevinWalker Alright

**Comment by ravinderk** [comment]
@DevinWalker pr updated with new changes.

File: assets/js/plugins/jquery.flot.orderBars.js [hunk 5]
```diff
@@ -88,8 +88,8 @@
         function getAxeMinMaxValues(series,AxeIdx){
             var minMaxValues = new Array();
             for(var i = 0; i < series.length; i++){
-                minMaxValues[0] = series[i].data[0][AxeIdx];
-                minMaxValues[1] = series[i].data[series[i].data.length - 1][AxeIdx];
+                minMaxValues[0] = (series[i].data[0]) ? series[i].data[0][AxeIdx]: null;
```
Comment (DevinWalker) [inline assets/js/plugins/jquery.flot.orderBars.js]: Has this been updated by you or did you update the plugin via bower?

Comment (DevinWalker) [inline assets/js/plugins/jquery.flot.orderBars.js]: In other words... will this be overwritten and break if it's modified?

Comment (ravinderk) [inline assets/js/plugins/jquery.flot.orderBars.js]: @DevinWalker This was updated by gulp and it will be good if we keep them in their original version. Pr updated.

File: includes/scripts.php [hunk 6]
```diff
@@ -310,6 +310,18 @@ function give_load_admin_scripts( $hook ) {
...
 		'dismiss_notice_text'            => __( 'Dismiss this notice.', 'give' ),
+		'bulk_action' => array(
+			'delete'         => array(
+				'zero_payment_selected' => __( 'You must choose at least one or more payments to delete.', 'give' ),
+				'delete_payment'        => __( 'Are you sure you want to permanently delete this donation?', 'give' ),
+				'delete_payments'       => __( 'Are you sure you want to permanently delete the selected {payment_count} donations?', 'give' ),
+			),
+			'resend_receipt' => array(
+				'zero_recipient_selected' => __( 'You must choose at least one or more recipients to resend the email receipt.', 'give' ),
+				'resend_receipt'          => __( 'Are you sure you want to resend the email receipt to this recipients?', 'give' ),
```
Comment (DevinWalker) [inline includes/scripts.php]: Minor typo: should be "recipient"

Comment (ravinderk) [inline includes/scripts.php]: Typo fixed
