### PR TITLE
Issues/1925

### LINKED ISSUE #1925: Incorrect currency displaying under Donations > Donors
## Issue Overview
After running the upgrade routines within 1.8.12 I noticed the currency is incorrectly displaying as Euros:

I replicated this on two separate environments. I have USD $ set as my global currency.

## Expected Behavior
Currency sign displays correctly everywhere.

## Current Behavior
It is incorrectly displayed.

## Steps to Reproduce (for bugs)

1. Switch to 1.8.12 
2. Run upgrade routines
3. View donors

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will resolve #1925 

## How Has This Been Tested?

Review donor table and donor detail page

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/formatting.php [hunk 1]
```diff
@@ -371,7 +371,7 @@ function give_format_decimal( $amount, $dp = false, $sanitize = true ) {
  */
 function give_currency_filter( $price = '', $currency = '', $decode_currency = false ) {
 
-	if ( empty( $currency ) ) {
+	if ( empty( $currency ) || ! array_key_exists( (string) $currency, give_get_currencies() ) ) {
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker Review this condition improvement

**Comment by ravinderk** [comment]
@DevinWalker Merging this PR.

File: includes/formatting.php (hunk 1 above)
Comment (DevinWalker) [inline includes/formatting.php]: Looks good!
