### PR TITLE
Issues/1849

### LINKED ISSUE #1849: When period used as thousands separator, the total is wrong and minimum amount alert triggers
## Issue Overview
When period used as thousands separator, the total is wrong and minimum amount alert triggers

## Current Behavior
Some countries use a period as the thousands separator. Currently, when that is set it makes the total amount incorrect and triggers the minimum donation alert falsely.

## Expected Behavior
Periods should be supported as thousands separators correctly.

## Steps to Reproduce (for bugs)
1. Go to "Donations > Settings > General > Currency" and set the thousands separator to a period (.). The decimal seperator and the number of decimals won't matter.
2. On your form, set a minimum $20 donation.
3. Test a donation by donating over $1,000 (in order to trigger a thousand separator). The totla will be reflected as $1 instead of $1,000. You should then see a message like this:
image

## Customers reporting this issue:
* https://secure.helpscout.net/conversation/391650991/8704/?folderId=672201
* https://secure.helpscout.net/conversation/398883082/8972/?folderId=672201

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will resolve #1849 
This PR can affect all possible place where we are sanitizing and showing amount like email, donation form, donations listing, donor list etc.

## How Has This Been Tested?

Note: Before following the testing instruction you have to run updates otherwise you will get the same issue. Please also test this without updates, for checking are you getting any issue with currency formatting. I added support for INR currency in amount formatting and human readable amount function.

**Settings**
During testing trying different combinations of decimal ( `,`, `.` ) and thousand ( `,`, `.`, ` `) separators with decimal precision (0-5 [ 6 precision is core standard now]).
**Note:** Core will validate decimal and thousand separators from now. here are few cases:
1. Decimal and thousands separator can not be same.
2. Number decimal can not be non-zero if decimal separator is set to empty.
3. Six number of the decimal is core standard.

To test this PR, you can test following thing:
1. Add a new donation from front end and check following things
   a. Email receipt
   b. Confirmation page receipt
   c. Donation in list and detail page
   d. Log entry
   e. Donor count
   f. Forn earnings
   g. Reports  
2. Perform following the action on donation and review step1 sublist from point `c` again.
   a. Update donation amount
   b. Change donor
   c. Chnage form 
3. Review step 1 and 2 with following addon also:
   a. Payment gateways: stripe. paypal etc.
   b. Recurring donation
   c. Manual donation
   b. Email reports
   c. Fee recovery

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/admin/admin-filters.php [hunk 1]
```diff
@@ -26,7 +27,56 @@
...
+	$old_value     = $value;
+
+	if ( isset( $_POST['decimal_separator'] ) ) {
+		$value         = ! empty( $_POST['decimal_separator'] ) ? $value : 0;
+		$value_changed = true;
+	}
+
+	// Check if
+	if ( $value_changed && ( $old_value != $value ) ) {
+		Give_Admin_Settings::add_error( 'give-number-decimal', __( '\'Number of Decimals\' automatically set to zero because \'Decimal Separator\' can not empty.', 'give' ) );
```
Comment (ravinderk) [inline includes/admin/admin-filters.php]: @DevinWalker review this message text.

File: includes/admin/admin-filters.php [hunk 2]
```diff
@@ -26,7 +27,56 @@
...
+	}
+
+	$value = absint( $value );
+
+	if( 6 <= $value ) {
+		$value = 5;
```
Comment (ravinderk) [inline includes/admin/admin-filters.php]: @DevinWalker Let me know you want to show admin message while we auto set number of decimal to 5 when admin trying to set it to 6 or more than 6

File: includes/admin/admin-filters.php [hunk 3]
```diff
@@ -26,7 +27,56 @@
...
+ * @return  mixed
+ */
+function __give_validate_decimal_separator_setting_field( $value ) {
+	$thousand_separator = give_clean( $_POST['thousands_separator'] );
+	$decimal_separator  = give_clean( $_POST['decimal_separator'] );
+
+	if ( $decimal_separator === $thousand_separator ) {
+		$value                    = '';
+		$_POST['number_decimals'] = 0;
+		Give_Admin_Settings::add_error( 'give-decimal-separator', __( '\'Decimal Separator\' automatically set to empty because it can not equal to \'Thousand Separator\'', 'give' ) );
```
Comment (ravinderk) [inline includes/admin/admin-filters.php]: @DevinWalker review this message text

File: includes/admin/upgrades/upgrade-functions.php [hunk 4]
```diff
@@ -115,6 +115,24 @@ function give_show_upgrade_notices( $give_updates ) {
 			'callback' => 'give_v189_upgrades_levels_post_meta_callback',
 		)
 	);
+
+	// v1.8.12 Upgrades
+	$give_updates->register(
```
Comment (ravinderk) [inline includes/admin/upgrades/upgrade-functions.php]: @DevinWalker form and payment updates

File: includes/admin/upgrades/upgrade-functions.php [hunk 5]
```diff
@@ -115,6 +115,24 @@ function give_show_upgrade_notices( $give_updates ) {
...
+		array(
+			'id'       => 'v1812_update_amount_values',
+			'version'  => '1.8.12',
+			'callback' => 'give_v1812_update_amount_values_callback',
+		)
+	);
+
+	// v1.8.12 Upgrades
+	$give_updates->register(
```
Comment (ravinderk) [inline includes/admin/upgrades/upgrade-functions.php]: @DevinWalker door updates for purchage value standarization

File: includes/formatting.php [hunk 6]
```diff
@@ -45,7 +49,70 @@ function give_get_price_thousand_separator() {
  * @return mixed
  */
 function give_get_price_decimal_separator() {
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker This function update to return default decimal separator.

File: includes/formatting.php [hunk 7]
```diff
@@ -45,7 +49,70 @@ function give_get_price_thousand_separator() {
...
+/**
+ * Sanitize Amount before saving to database
+ *
+ * @since      1.8.12
+ *
+ * @param  int|float|string $number Expects either a float or a string with a decimal separator only (no thousands)
+ *
+ * @return string $amount Newly sanitized amount
+ */
+function give_sanitize_amount_for_db( $number ) {
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker Helper function to sanitize amount for DB

File: includes/formatting.php [hunk 8]
```diff
@@ -45,7 +49,70 @@ function give_get_price_thousand_separator() {
...
+ *
+ * @since      1.8.12
+ *
+ * @param  int|float|string $number     Expects either a float or a string with a decimal separator only (no thousands)
+ * @param  int|bool         $dp         Number of decimals
+ * @param  bool             $trim_zeros From end of string
+ *
+ * @return string $amount Newly sanitized amount
+ */
+function give_maybe_sanitize_amount( $number, $dp = false, $trim_zeros = false ) {
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker Helper function which used inside the core. It will decide whom to sanitize.

File: includes/formatting.php [hunk 9]
```diff
@@ -129,27 +196,77 @@ function give_sanitize_amount( $number, $dp = false, $trim_zeros = false ) {
...
 
-	$formatted = number_format( $amount, $decimals, $decimal_sep, $thousands_sep );
+	if ( ! empty( $amount ) ) {
+		// Sanitize amount before formatting.
+		$amount = ! empty( $args['sanitize'] ) ?
+			give_maybe_sanitize_amount( $amount, $decimals ) :
+			number_format( $amount, $decimals, '.', '' );
+
+		switch ( $currency ) {
+			case 'INR':
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker INR support in format amount function.

File: includes/formatting.php [hunk 10]
```diff
@@ -200,14 +336,17 @@ function give_human_format_large_amount( $amount ) {
...
- * @param int|float|string $amount Formatted or sanitized price
- * @param int|bool         $dp number of decimals
+ * @param int|float|string $amount   Formatted or sanitized price
+ * @param int|bool         $dp       number of decimals
+ * @param bool             $sanitize Whether or not sanitize number
  *
  * @return string $amount Newly formatted amount or Price Not Available
  */
-function give_format_decimal( $amount, $dp = false ) {
+function give_format_decimal( $amount, $dp = false, $sanitize = true ) {
```
Comment (ravinderk) [inline includes/formatting.php]: @DevinWalker decimal format fx updated

File: tests/unit-tests/tests-formatting.php [hunk 11]
```diff
@@ -104,18 +104,30 @@ function give_sanitize_amount_provider() {
 	 *
```
Comment (ravinderk) [inline tests/unit-tests/tests-formatting.php]: @DevinWalker Review update and new unit tests

Comment (DevinWalker) [inline tests/unit-tests/tests-formatting.php]: That's nice!

File: includes/admin/admin-filters.php (hunk 1 above)
Comment (DevinWalker) [inline includes/admin/admin-filters.php]: Thanks I edited it slightly

**Comment by DevinWalker** [comment]
@ravinderk this is working fine for me. I'll get @mathetos to confirm and then merge it. Great job on this one.

**Comment by DevinWalker** [comment]
@ravinderk I'm seeing a PHP notice with these settings:

**Comment by mathetos** [comment]
Looks good, but there is one bug I'm finding:

On multi-level forms the donation receipt and the email tag are not reflecting the level correctly. This donation was made with one of the levels on the form, but it is reflected as "Custom Amount":

image

**Comment by mathetos** [comment]
Also @ravinderk just confirming that after running the database update the issue above is still present.

**Comment by ravinderk** [comment]
@mathetos @DevinWalker Both issue fixed.

**Comment by DevinWalker** [comment]
Nice! It's working well for me. I'm merging. Good job on this one. 🎉
