### PR TITLE
Issue/2401

### LINKED ISSUE #2401: Donations should be easily identified for form with Set Donation Method
## Issue Overview
I've created a donation form with custom amount enabled and performed 2 different donations with it. Then, checking the donations section it is not easily identified whether which donation is of regular amount and which is of custom amount.

Areas to add the possible solution:
- Donation Listing page in admin.
- Donation Detail page in admin.
- Donation Receipt in front end.

**Note:** I can reproduce this issue with `release 1.8.17` as well as `release 2.0`

## Expected Behavior
image

## Current Behavior

image

## Possible Solution
Adding a text `Custom Amount`, in similar way of multi level forms will make this more effective.

## Steps to Reproduce (for bugs)
1. Create a donation form with `Set Donation` Method and Custom Amount enabled
2. Create 1 donation with actual amount of that form and create another donation with random amount.
3. Check both the donations in admin
4. You won't be easily identifying which one is the actual amount of the donation form, unless you check the amount in donation form.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by mehul0810**
## Description
This PR resolves #2401 

## How Has This Been Tested?
I've manually tested this with the following possibilities:
- Set Donation Form with Custom Amount
- Set Donation Form with Actual Amount 
- Multi Level Donation Form with Custom Amount
- Multi Level Donation Form with Actual Amount as per the donation level selected.

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/class-give-donate-form.php [hunk 1]
```diff
@@ -651,6 +650,45 @@ public function is_custom_price_mode() {
...
+	 * Determine if custom price mode is enabled or disabled
+	 *
+	 * @since  1.8.18
+	 * @access public
+	 *
+	 * @param string|float $amount Donation Amount.
+	 *
+	 * @return bool
+	 */
+	public function is_custom_price( $amount ) {
```
Comment (ravinderk) [inline includes/class-give-donate-form.php]: @DevinWalker I added a new helper function to detected, price_id `custom` or not on basis of amount
