### PR TITLE
Receipt Access Improvements

### LINKED ISSUE #2304: Problem with email access due to complication with #1790
@Benunc commented on [Tue Nov 07 2017](https://github.com/WordImpress/Give-Recurring-Donations/issues/418)

## Issue Overview

Currently if email access is enabled, donors cannot access their donation history as expected.

## Expected Behavior
The Give_subscriptions shortcode should work correctly.

## Current Behavior
screen shot 2017-11-07 at 11 32 47 am

## Possible Solution
Review complication with #1790 causing email access to not work as expected. 

## Steps to Reproduce (for bugs)

**Original steps from @Benunc**
1. On Give 1.8.16 and Recurring 1.4 branch (pre-release)
2. Create some subscriptions, as well as a page with the [give_subscriptions] shortcode.
3. Ensure that email access is enabled.
4. In an incognito browser, navigate to the page with the above shortcode on it
5. Attempt to enter a valid email that has made a recurring donation on the site.

**I was able to reproduce with the donation history page, and other locations the email access is in use. Essentially, email access is not working now.**

You will get the above error 

> Error: It looks like that email address provided and access token of the link does not match.

## Related issues
https://github.com/WordImpress/Give/issues/1790

### PR DESCRIPTION
**Pull request by mehul0810**
## Description
This PR resolves #2304 and #2023 

## How Has This Been Tested?
I've tested this manually with the below scenario's:
- Email Access Disabled
- Email Access Enabled
- After completing donation and accessing the history

@DevinWalker Can you verify and confirm the content of email when email access is enabled?

## Types of changes
Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/class-give-email-access.php [hunk 1]
```diff
@@ -204,6 +204,12 @@ public function send_email( $customer_id, $email ) {
 			'give_nl' => $verify_key,
 		), give_get_history_page_uri() );
 
+		if ( ! empty( $_GET['payment_key'] ) ) {
+			$access_url = add_query_arg( array(
+				'payment_key' => $_GET['payment_key'],
```
Comment (ravinderk) [inline includes/class-give-email-access.php]: @mehul0810 Use `give_clean`

File: includes/class-give-email-access.php [hunk 2]
```diff
@@ -255,6 +261,8 @@ public function check_for_token() {
 				}
 			}
 
+			// Set Receipt Access Session.
+			Give()->session->set( 'receipt_access', true );
```
Comment (ravinderk) [inline includes/class-give-email-access.php]: @mehul0810 Reciept access depends upon `payment_key`, right? This should be set conditionally, right?

Comment (mehul0810) [reply includes/class-give-email-access.php]: @ravinderk Yes.. It is dependent on it and it is set conditionally only. See the condition on L256 `if( ! empty($token)){`
