### PR TITLE
Fix issue 1929

### LINKED ISSUE #1929: {user_email} and {billing_address} does not reflect value within Email or Preview Donation Receipt
## Issue Overview

Currently, `{user_email}` and `{billing_address}` email tag does not reflect it's valued while previewing Donation receipt.

## Expected Behavior

As `{user_email}` and `{billing_address}`  get value if the Donor has filled their information while processing donation form.

I think we should have to display below value if Admin preview Donation receipt as a Default:
`{user_email}` => Admin email address. 
`{billing_address}`  => blank value.

## Current Behavior

Currently, It does not reflect default value and return email tag.

screenshot-givewpcore dev1 in-2017-07-31-13-18-57 1

## Possible Solution
While preview default Donation receipt we need to show default value like below:
`{user_email}` => Admin email address. 
`{billing_address}`  => blank value.

## Steps to Reproduce (for bugs)

1. Go to  Settings > Donation Receipt
2. Add {user_email} and {billing_address} email tag into Donation Receipt and preview Donation receipt.
3. It will return email tag as it is.

## Related Issues and/or PRs

Working on PR.

## Todos
- [x] Tests

### PR DESCRIPTION
**Pull request by jaydeeprami**
## Description

fix #1929 

## How Has This Been Tested?

- Give 1.8.12 branch
- Latest WordPress
- Preview all email tags.

## Screenshots (jpeg or gifs if applicable):
screenshot-givewpcore dev1 in-2017-07-31-15-33-10

## Types of changes

Set Preview for `{user_email}` and  `{billing_address}`.
For `{user_email}` default User email address.
For `{billing_address}` set blank value for preview.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/emails/template.php [hunk 1]
```diff
@@ -78,6 +78,8 @@ function give_email_preview_template_tags( $message ) {
 	$message = str_replace( '{name}', $user->display_name, $message );
 	$message = str_replace( '{fullname}', $user->display_name, $message );
 	$message = str_replace( '{username}', $user->user_login, $message );
+	$message = str_replace( '{user_email}', $user->user_email, $message );
+	$message = str_replace( '{billing_address}', '', $message );
```
Comment (DevinWalker) [inline includes/emails/template.php]: Just use a fake address here like:

 > 123 Test Street, Unit 222
> Somewhere Town, CA, 92101

If it's blank that will confuse people.

Comment (DevinWalker) [inline includes/emails/template.php]: Ensure there's a link break as well. Thanks!

Comment (jaydeeprami) [inline includes/emails/template.php]: @DevinWalker , I have added default address with line break. Thanks,
default address
