### PR TITLE
Issues/1617

### LINKED ISSUE #1617: give_stats_* transients filling up database unnecessarily
## Issue Overview
I just took a look at transient manager on multiple environments and noticed the number of expired transients like `give_stats_7d37f45d6c4ed54` was excessive.

**Local:**

**Second Environment:**

## Expected Behavior
No unnecessary expired transients fill database.

## Current Behavior
There is an excessive number of expired transients.

## Possible Solution
Review why transient is being created. Clear expired stat transients on a weekly basis.

## Steps to Reproduce (for bugs)
1. Install the Transient Manager plugin
2. Review logs under WP-Admin > Tools > Transients 

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This Pr will fix #1617 

## Types of changes

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ravinderk** [comment]
@DevinWalker Few point from this PR:
1. I added [`Give_Cache`](https://github.com/ravinderk/Give/blob/f9af10b7a180d8e7e79dad82c5d4882a29ddf30b/includes/class-give-cache.php) class, in which I am using an option to store values with expiration timestamps.

2. I added automatic upgrades to remove existing caches values
for ref: https://github.com/WordImpress/Give/pull/1622/files#diff-fe0e36d5cf90056ccea283fd3c6daa71

3. Implemented for stat and logging.
for ref: https://github.com/WordImpress/Give/pull/1622/files#diff-30e950f974f511ffad88200faff49510

4. Tests added
for ref: https://github.com/WordImpress/Give/pull/1622/files#diff-6e761737f75590676e65a85f90ebd6d8

**Question:** There are still lot of transients we are using in our code, they are around `20`. Can I update them all?

**Comment by DevinWalker** [comment]
@ravinderk yes, please update all transients to use the new class.

File: includes/admin/upgrades/upgrade-functions.php [hunk 1]
```diff
@@ -820,3 +824,42 @@ function give_v18_renamed_core_settings() {
...
+ */
+function give_v187_upgrades(){
+	global $wpdb;
+
+	/**
+	 * Upgrade 1: Remove stat and cache transients.
+	 */
+	$cached_options = $wpdb->get_col(
+		$wpdb->prepare(
+			"SELECT * FROM {$wpdb->options} where (option_name LIKE '%%%s%%' OR option_name LIKE '%%%s%%')",
```
Comment (ravinderk) [inline includes/admin/upgrades/upgrade-functions.php]: @DevinWalker I designed different model on how cached value store in DB with a timestamp and I am removing all cache without checking expiration to upgrade every cache value.
For Ref: https://github.com/WordImpress/Give/pull/1622/files/f9af10b7a180d8e7e79dad82c5d4882a29ddf30b#diff-338475964ff644868092ed67b2a5cb0eR149
